# Generated by Django 4.2.7 on 2023-11-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField()),
                ('completed', models.BooleanField(default=False)),
                ('task_description', models.CharField(blank=True, null=True)),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_app.list')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField()),
                ('completed', models.BooleanField(default=False)),
                ('parentTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_app.task')),
            ],
        ),
    ]
