# Generated by Django 4.2.7 on 2023-11-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
    ]
