# Generated by Django 4.2.7 on 2023-11-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0003_remove_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='parentTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='list_app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='list_app.list'),
        ),
    ]
